---
  - name: Install Nginx
    become: yes
    yum:
      name: nginx
      state: latest

  - name: Copy Nginx Config
    become: yes
    template: 
      src: nginx.conf
      dest: /etc/nginx/conf.d/default.conf
    register: nginx_config_update_result

  - set_fact: 
      is_nginx_config_updated: nginx_config_update_result.changed

  - name: Start Nginx
    become: yes
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Restart Nginx
    become: yes
    service: 
      name: nginx
      state: restarted
    when: is_nginx_config_updated