---
  - name: Install Nginx
    become: yes
    yum:
      name: nginx
      state: latest

  - name: Copy Nginx Config
    become: yes
    template: 
      src: nginx.conf
      dest: /etc/nginx/conf.d/default.conf

  - name: Start Nginx
    become: yes
    service:
      name: nginx
      state: started
      enabled: yes