---
- hosts: box1
  vars_files: 
    - ./config/config.yml 
  tasks:
    - name: Include nodejs role
      include_role: 
        name: nodejs
      vars:
        node_version: '7.2.0'

    - name: Copy nginx config
      become: yes
      copy: 
        src: ./config/default.conf
        dest: /etc/nginx/conf.d/default.conf

    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
        enabled: yes
- hosts: box2
  vars_files: 
    - ./config/config.yml 
  tasks:
    - name: Include nodejs role
      include_role: 
        name: nodejs  
      vars:
        node_version: '7.4.0'  

 
