---
- hosts: box1
  vars_files: 
    - ./config/config.yml 
  tasks:
    - name: Include nodejs role
      include_role: 
        name: nodejs
      vars:
        node_version: "{{node_version_box1}}"
    - name: Include nginx role
      include_role: 
        name: nginx

- hosts: box2
  vars_files: 
    - ./config/config.yml 
  tasks:
    - name: Include nodejs role
      include_role: 
        name: nodejs  
      vars:
        node_version: "{{node_version_box1}}"

