---
  - name: Install Node Repo 
    become: yes
    yum_repository: 
      name: noderpm
      description: node from rpm
      baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
      enabled: yes
      gpgcheck: no

  - name: Install Nodejs
    become: yes
    yum: 
      name: nodejs
      state: latest
