---
  - name: Install Node repo 
    become: yes
    yum_repository: 
      name: noderpm
      description: node from rpm
      baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
      enabled: yes
      gpgcheck: no

  - name: Install services
    become: yes
    yum: 
      name: "{{item}}"
      state: latest
    with_items:
      - nodejs-{{node_version}}
      - nginx
